<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Formation;
use App\Models\User;

class FormationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first() ?? User::first();
        $adminId = $admin ? $admin->id : null;

        $formations = [
            // ==========================================
            // 1. AUDIT, COMPTABILITÉ & FINANCE (ACF)
            // ==========================================
            [
                'code' => 'ACF-001',
                'title' => 'Principes de la comptabilité publique',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Comprenez les règles et mécanismes clés de la comptabilité publique pour assurer une gestion efficace et transparente des finances publiques.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-002',
                'title' => 'Comptabilité analytique selon la méthode ABC',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez la méthode ABC pour analyser les coûts par activité et améliorer la rentabilité et la performance de votre organisation.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-003',
                'title' => 'La comptabilité analytique: un outil d d\'aide à la décision',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les méthodes d d\'analyse des coûts pour optimiser les performances et guider les choix stratégiques de votre organisation.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-004',
                'title' => 'Comptabilité matière et gestion prévisionnelle des stocks',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les outils de gestion des stocks pour anticiper les besoins, réduire les coûts et améliorer la performance de votre organisation.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-005',
                'title' => 'Etre chef comptable: maitriser les aspects fondamentaux',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les missions clés du chef comptable pour piloter efficacement la comptabilité et assurer la conformité des opérations financières.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-006',
                'title' => 'Comptabilité & Fiscalité des immobilisations',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez le traitement comptable et fiscal des immobilisations pour garantir la conformité et optimiser la gestion du patrimoine de l entreprise.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-007',
                'title' => 'Comprendre les normes comptables internationales & réussir le reporting',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Apprenez à appliquer les normes IFRS pour un reporting financier clair, fiable et conforme aux exigences.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-008',
                'title' => 'Financement de projets : Évaluer les risques et établir un plan de financement',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez l évaluation des risques et la planification financière pour garantir le succès et la viabilité des projets.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-009',
                'title' => 'Comprendre les normes comptables IAS/IFRS',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les normes IAS/IFRS pour garantir un reporting financier conforme et transparent.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-010',
                'title' => 'Comptabilité Financière & analyse des états Financières (Normes IFRS)',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Analysez les états financiers pour évaluer la performance et la santé d une entreprise.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-011',
                'title' => 'Maitrise de la comptabilité fournisseurs',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Optimisez la gestion des comptes fournisseurs pour assurer la fiabilité et la fluidité des paiements.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-012',
                'title' => 'L\'intelligence artificielle contre la fraude financière',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Découvrez comment l IA détecte et prévient efficacement les fraudes financières et opérationnelles.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-013',
                'title' => 'Audit & contrôle de gestion des Finances publiques',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Apprenez à contrôler et auditer les finances publiques pour garantir transparence et conformité.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-014',
                'title' => 'Audit interne et audit externe',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Comprenez les différences et les méthodes d audit interne et externe pour renforcer la gouvernance.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-015',
                'title' => 'Préparation & exécution des lois de finances',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les étapes clés de préparation et d exécution budgétaire.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-016',
                'title' => 'Préparation, programmation et exécution budgétaire axées sur les résultats',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez la préparation, la programmation et l exécution du budget public.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-017',
                'title' => 'Mise en œuvre de la loi organique relative aux lois de finances (LOLF)',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Comprenez et appliquez les principes de la LOLF dans la gestion publique.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-018',
                'title' => 'Procédure de décaissement de la Banque Mondiale & système de paiement',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les procédures de décaissement et les systèmes de paiement internationaux.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-019',
                'title' => 'Tableau des opérations financières (TOF)',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Comprenez la structure, les enjeux et l analyse du tableau TOF.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-020',
                'title' => 'Mobilisation et gestion des ressources budgétaires des collectivités',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Optimisez la mobilisation, la gestion et le suivi des ressources budgétaires locales.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-021',
                'title' => 'Evaluation du système et gestion des finances publiques',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Évaluez la performance du système et gérez efficacement les finances publiques.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-023',
                'title' => 'Finance islamique: fondements, mécanismes et apports',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Découvrez les principes, outils et enjeux clés de la finance islamique.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-024',
                'title' => 'Diagnostic financier & mesure des performances financières',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez l analyse financière pour évaluer la performance et la rentabilité.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-025',
                'title' => 'Construction & utilisation du tableau de bord financier',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez création, analyse et suivi efficace d un tableau financier.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-026',
                'title' => 'Présentation des états financiers en IFRS',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Comprenez normes IFRS pour préparer et présenter des états financiers fiables.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-027',
                'title' => 'Mécanismes de financement des investissements des entreprises',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Explorez sources et outils pour financer efficacement les investissements d entreprise.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'ACF-028',
                'title' => 'Recouvrement des créances: aspects comptables, financiers & juridiques',
                'type' => 'certifiante',
                'domain' => 'Audit, Comptabilité & Finance',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Apprenez gestion, suivi et aspects juridiques du recouvrement des créances.',
                'status' => 'active',
                'created_by' => $adminId,
            ],

            // ==========================================
            // 2. PROJET & PROGRAMMES DE DÉVELOPPEMENT (PPD)
            // ==========================================
            [
                'code' => 'PPD-001',
                'title' => 'Contrôle interne et audit de projet en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les outils et méthodes du contrôle interne et de l audit pour garantir la conformité et la performance des projets en Afrique.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-002',
                'title' => 'Contrôle et évaluation des projets en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Apprenez à contrôler efficacement les projets de développement et à évaluer leur performance sur le terrain africain.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-003',
                'title' => 'Les processus et outils clés de planification et Suivi-Evaluation des projets de développement',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Utilisez les outils modernes de planification, suivi et évaluation pour assurer le succès des projets en Afrique.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-004',
                'title' => 'Gestion comptable et financière des projets de développement - Elaboration des états financiers',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Apprenez à gérer la comptabilité, les budgets et à élaborer des états financiers pour les projets de développement.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-005',
                'title' => 'Réussir la clôture des projets et programmes de développement en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les étapes de la clôture des projets, du rapport final à la capitalisation des acquis.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-006',
                'title' => 'La planification stratégique, financière et opérationnelle des projets en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Intégrer une approche globale pour planifier, piloter et financer efficacement vos projets et programmes.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-007',
                'title' => 'Planification, exécution et suivi/évaluation des projets en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Acquérez une vision complète du cycle de vie d un projet, de la planification à l évaluation.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-008',
                'title' => 'Financement de projets : Evaluer les risques et etablir un plan de financement',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Évaluez les risques financiers et établissez un plan de financement solide pour vos projets en Afrique.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-009',
                'title' => 'Dispositions pour réussir le Montage de projets et la mobilisation de Ressources auprès des bailleurs de fonds',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Apprenez à construire des projets solides et mobilisez efficacement les ressources auprès des bailleurs.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-010',
                'title' => 'Devenir auditeur de projet de développement en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Acquérez les compétences clés pour auditer les projets de développement et garantir leur efficacité.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-011',
                'title' => 'Coordonnateur des projets et programmes de développement en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Formez-vous pour devenir un leader stratégique dans la coordination de projets en Afrique.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-012',
                'title' => 'La planification des tâches et processus de management des projets en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Maîtrisez les techniques de planification et de management pour gérer efficacement les tâches d un projet.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PPD-013',
                'title' => 'Devenir spécialiste en communication de projet de développement',
                'type' => 'certifiante',
                'domain' => 'Projets & Programmes de Développement',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Devenez spécialiste en communication et valorisez les résultats de vos projets auprès des parties prenantes.',
                'status' => 'active',
                'created_by' => $adminId,
            ],

            // ==========================================
            // 3. DÉVELOPPEMENT PERSONNEL & SOFT SKILLS (DPS)
            // ==========================================
            [
                'code' => 'DPS-001',
                'title' => 'Gestion du temps & des priorités',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Formation pratique pour maîtriser la gestion du temps et des priorités afin d améliorer l efficacité et réduire le stress au quotidien.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-002',
                'title' => 'Management des conflits: Comprendre, prévenir et résoudre les conflits dans un environnement professionnel',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Apprenez à comprendre, prévenir et résoudre efficacement les conflits dans un environnement professionnel.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-003',
                'title' => 'Intelligence émotionnelle: Développer sa capacité à gérer ses émotions et celles des autres',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Apprenez à maîtriser vos émotions et à mieux comprendre celles des autres pour améliorer vos relations professionnelles.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-004',
                'title' => 'Développement personnel et affirmation de soi',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Renforcez votre confiance et vos compétences pour atteindre pleinement votre potentiel personnel et professionnel.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-005',
                'title' => 'Design thinking au service des ressources humaines',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Apprenez à innover et co-créer des solutions centrées sur l humain pour transformer la gestion des talents.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-006',
                'title' => 'Design thinking pour les entrepreneurs',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Maîtrisez une approche créative et centrée utilisateur pour concevoir des produits et services innovants.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-007',
                'title' => 'Optimisation de la performance individuelle et collective',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Développez des stratégies efficaces pour améliorer la productivité et la collaboration au sein de vos équipes.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-008',
                'title' => 'Soft skills essentielles en entreprise',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Développez les compétences comportementales indispensables pour exceller dans le monde professionnel.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-009',
                'title' => 'Adaptation au changement: comment développer sa résilience et s\'adapter',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Apprenez à renforcer votre résilience pour mieux gérer les transitions et vous adapter efficacement aux nouvelles situations.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-010',
                'title' => 'Techniques de communication assertive & négociation',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Maîtrisez les outils et méthodes pour communiquer clairement, écouter activement et convaincre efficacement.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DPS-011',
                'title' => 'Développer son esprit critique et sa prise de décision',
                'type' => 'certifiante',
                'domain' => 'Soft Skills & Développement Personnel',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Apprenez à analyser, questionner et évaluer l information pour prendre des décisions éclairées et pertinentes.',
                'status' => 'active',
                'created_by' => $adminId,
            ],

            // ==========================================
            // 4. PROJET ÉDUCATIF EN AFRIQUE (PEA)
            // ==========================================
            [
                'code' => 'PEA-001',
                'title' => 'Gouvernance et pilotage du secteur éducatif Africain',
                'type' => 'certifiante',
                'domain' => 'Projet Éducatif en Afrique',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Boostez votre impact dans l éducation en Afrique avec une formation stratégique sur la gouvernance et le pilotage efficace des systèmes éducatifs.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PEA-002',
                'title' => 'Mise en oeuvre d\'une stratégie Africaine nationale de l\'éducation',
                'type' => 'certifiante',
                'domain' => 'Projet Éducatif en Afrique',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Boostez votre impact dans l éducation en Afrique avec une formation stratégique sur la mise en œuvre des politiques nationales.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PEA-003',
                'title' => 'Pratiques et dispositifs pour une Amélioration de la qualité de l\'éducation en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projet Éducatif en Afrique',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Boostez votre impact dans l éducation en Afrique avec une formation pratique sur les dispositifs innovants pour améliorer la qualité.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PEA-004',
                'title' => 'Suivi et évaluation d\'une stratégie africaine nationale d\'éducation',
                'type' => 'certifiante',
                'domain' => 'Projet Éducatif en Afrique',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Boostez votre impact dans l éducation en Afrique avec une formation stratégique sur le suivi et l évaluation efficaces.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PEA-005',
                'title' => 'Décentralisation en Education Africaine',
                'type' => 'certifiante',
                'domain' => 'Projet Éducatif en Afrique',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Boostez votre impact dans l éducation en Afrique avec une formation spécialisée sur la décentralisation pour une gestion locale.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PEA-006',
                'title' => 'Education au développement durable en Afrique',
                'type' => 'certifiante',
                'domain' => 'Projet Éducatif en Afrique',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Boostez votre impact dans l éducation en Afrique avec une formation engagée sur l intégration du développement durable.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'PEA-007',
                'title' => 'Leadership et gestion des établissements scolaires africains',
                'type' => 'certifiante',
                'domain' => 'Projet Éducatif en Afrique',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Boostez votre impact dans l éducation en Afrique avec une formation ciblée sur le leadership et la gestion d établissements scolaires.',
                'status' => 'active',
                'created_by' => $adminId,
            ],

            // ==========================================
            // 5. INFORMATIQUE & NTIC (INT)
            // ==========================================
            [
                'code' => 'INT-001',
                'title' => 'Audit & consulting en cyber security',
                'type' => 'certifiante',
                'domain' => 'Informatique & NTIC',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Évaluer la sécurité des systèmes d information, identifier les vulnérabilités et recommander les meilleures stratégies de protection.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'INT-002',
                'title' => 'Optimiser la performance & la sécurité des réseaux',
                'type' => 'certifiante',
                'domain' => 'Informatique & NTIC',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Configurer et maintenir une infrastructure réseau d entreprise hautement disponible, sécurisée et performante.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'INT-003',
                'title' => 'Investigation numérique & Computer Forensics',
                'type' => 'certifiante',
                'domain' => 'Informatique & NTIC',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Acquérir les techniques de collecte, préservation et analyse des preuves numériques lors de cyberattaques ou fraudes.',
                'status' => 'active',
                'created_by' => $adminId,
            ],

            // ==========================================
            // 6. E-COMMERCE & FINTECH (EF)
            // ==========================================
            [
                'code' => 'EF-014',
                'title' => 'L\'Intelligence Artificielle (IA) appliquée aux entreprises',
                'type' => 'certifiante',
                'domain' => 'E-Commerce, Fintech & Développement Durable',
                'duration' => '1 Semaine',
                'price' => 1900.00,
                'description' => 'Découvrir comment exploiter les outils d IA générative et l analyse de données pour automatiser les processus d affaires.',
                'status' => 'active',
                'created_by' => $adminId,
            ],

            // ==========================================
            // 7. MARCHÉS PUBLICS (MP)
            // ==========================================
            [
                'code' => 'MP-001',
                'title' => 'Exécution des marchés publics : suivi des contrats',
                'type' => 'certifiante',
                'domain' => 'Marchés Publics',
                'duration' => '2 Semaines',
                'price' => 3300.00,
                'description' => 'Sécuriser la passation et la gestion administrative, financière et juridique des marchés publics.',
                'status' => 'active',
                'created_by' => $adminId,
            ],

            // ==========================================
            // 8. FORMATIONS DIPLOMANTES (MBA, DOCTORAT)
            // ==========================================
            [
                'code' => 'MBA-MINI',
                'title' => 'Mini MBA - Fondamentaux du Management Général',
                'type' => 'diplomante',
                'domain' => 'Management & Governance',
                'duration' => '6 mois',
                'price' => null, // Sur devis
                'description' => 'Programme condensé de haut niveau conçu pour les cadres à fort potentiel souhaitant consolider leurs compétences transversales en leadership, finance et stratégie.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'MBA-EXEC',
                'title' => 'Executive MBA (EMBA) - Leadership Stratégique',
                'type' => 'diplomante',
                'domain' => 'Management & Governance',
                'duration' => '12 mois',
                'price' => null, // Sur devis
                'description' => 'Un cursus international d excellence conciliable avec une carrière active, préparant aux postes de direction générale et internationale.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DOC-EXEC',
                'title' => 'Doctorat Executive (DBA) - Recherche & Management Stratégique',
                'type' => 'diplomante',
                'domain' => 'Management & Governance',
                'duration' => '36 mois',
                'price' => null, // Sur devis
                'description' => 'Le plus haut niveau académique et professionnel pour concevoir des travaux de recherche appliquée aux problématiques réelles des organisations.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
        ];

        foreach ($formations as $data) {
            Formation::updateOrCreate(
                ['code' => $data['code']],
                $data
            );
        }
    }
}
