<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Formation;
use App\Models\User;

class FormationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first() ?? User::first();
        $adminId = $admin ? $admin->id : null;

        $formations = [

    // ==========================================
    // 1. PROJET ÉDUCATIF EN AFRIQUE (PEA) - 7 formations (2 Semaines / 3300€)
    // ==========================================
    [
        'code' => 'PEA-001',
        'title' => 'Élaboration et pilotage d’une politique nationale d’éducation',
        'type' => 'certifiante',
        'domain' => 'Projet Éducatif en Afrique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Définir les orientations stratégiques, coordonner les acteurs institutionnels et piloter la mise en œuvre des réformes du système éducatif national.',
    ],
    [
        'code' => 'PEA-002',
        'title' => 'Planification, carte scolaire et allocation des ressources éducatives',
        'type' => 'certifiante',
        'domain' => 'Projet Éducatif en Afrique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtriser les outils de diagnostic, la modélisation de la carte scolaire et l\'optimisation de l\'allocation des ressources humaines et matérielles.',
    ],
    [
        'code' => 'PEA-003',
        'title' => 'Financement, budgétisation et gestion financière du secteur éducatif',
        'type' => 'certifiante',
        'domain' => 'Projet Éducatif en Afrique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Élaborer des budgets de programmes crédibles, mobiliser des financements innovants et assurer une exécution financière transparente.',
    ],
    [
        'code' => 'PEA-004',
        'title' => 'Passation des marchés et gestion logistique dans les projets éducatifs',
        'type' => 'certifiante',
        'domain' => 'Projet Éducatif en Afrique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Sécuriser l\'approvisionnement en manuels, équipements scolaires et infrastructures éducatives selon les procédures nationales et internationales.',
    ],
    [
        'code' => 'PEA-005',
        'title' => 'Suivi, évaluation et mesure des acquis scolaires',
        'type' => 'certifiante',
        'domain' => 'Projet Éducatif en Afrique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Concevoir des dispositifs nationaux d\'évaluation des apprentissages, exploiter les indicateurs de performance et orienter les décisions pédagogiques.',
    ],
    [
        'code' => 'PEA-006',
        'title' => 'Gouvernance, décentralisation et partenariat école-communauté',
        'type' => 'certifiante',
        'domain' => 'Projet Éducatif en Afrique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Renforcer la gestion participative des établissements scolaires, responsabiliser les collectivités locales et impliquer les communautés éducatives.',
    ],
    [
        'code' => 'PEA-007',
        'title' => 'Amélioration de la qualité de l’éducation et gestion des réformes curriculaires',
        'type' => 'certifiante',
        'domain' => 'Projet Éducatif en Afrique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Piloter la révision des programmes scolaires, former les encadreurs pédagogiques et instaurer une culture d\'évaluation continue de la qualité.',
    ],

    // ==========================================
    // 2. PROJETS & PROGRAMMES DE DÉVELOPPEMENT (PPD) - 13 formations (2 Semaines / 3300€)
    // ==========================================
    [
        'code' => 'PPD-001',
        'title' => 'Méthodes de planification, suivi et évaluation axés sur les résultats',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtriser la gestion axée sur les résultats (GAR), élaborer le cadre logique et concevoir un dispositif de suivi-évaluation performant.',
    ],
    [
        'code' => 'PPD-002',
        'title' => 'Indicateurs de performance des projets et programmes',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Définir des indicateurs SMART, collecter et analyser des données fiables et mettre en place des tableaux de bord de pilotage stratégique.',
    ],
    [
        'code' => 'PPD-003',
        'title' => 'Gestion prévisionnelle et analyse des risques des projets',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Identifier, évaluer et hiérarchiser les risques techniques, financiers et environnementaux pour bâtir des plans de mitigation efficaces.',
    ],
    [
        'code' => 'PPD-004',
        'title' => 'Analyse financière et économique des projets de développement',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Évaluer la rentabilité financière (VAN, TRI) et l\'impact socio-économique des projets d\'investissement public et privé.',
    ],
    [
        'code' => 'PPD-005',
        'title' => 'Passation des marchés des projets selon les directives bailleurs',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Appliquer rigoureusement les procédures de passation des marchés de la Banque Mondiale, de la BAD et de l\'Union Européenne.',
    ],
    [
        'code' => 'PPD-006',
        'title' => 'Gestion administrative, logistique et matérielle des projets',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Organiser la chaîne logistique, gérer le parc matériel et administrer les contrats de projets de développement.',
    ],
    [
        'code' => 'PPD-007',
        'title' => 'Audit opérationnel et financier des projets et programmes',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Conduire les missions d\'audit interne et externe, vérifier l\'éligibilité des dépenses et prévenir les anomalies de gestion.',
    ],
    [
        'code' => 'PPD-008',
        'title' => 'Mobilisation des ressources et négociation avec les bailleurs',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Monter des requêtes de financement convaincantes, négocier les conventions de crédit et fidéliser les partenaires financiers.',
    ],
    [
        'code' => 'PPD-009',
        'title' => 'Management d\'équipe et leadership dans les projets de développement',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Fédérer des équipes pluridisciplinaires, piloter la performance collective et résoudre les conflits en environnement multiculturel.',
    ],
    [
        'code' => 'PPD-010',
        'title' => 'Genre, inclusion sociale et développement durable dans les projets',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Intégrer les dimensions genre, vulnérabilité sociale et sauvegarde environnementale tout au long du cycle de vie du projet.',
    ],
    [
        'code' => 'PPD-011',
        'title' => 'Clôture, pérennisation et capitalisation des acquis d\'un projet',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Préparer les plans de sortie, assurer le transfert aux bénéficiaires et documenter les bonnes pratiques pour les futures interventions.',
    ],
    [
        'code' => 'PPD-012',
        'title' => 'Gestion des projets d\'infrastructures et d\'aménagement',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Superviser les chantiers, veiller au respect des délais et des coûts et coordonner les maîtrises d\'ouvrage et maîtrises d\'œuvre.',
    ],
    [
        'code' => 'PPD-013',
        'title' => 'Communication institutionnelle et plaidoyer pour les projets',
        'type' => 'certifiante',
        'domain' => 'Projets & Programmes de Développement',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Valoriser les résultats obtenus auprès des parties prenantes, concevoir des supports de plaidoyer et gérer les relations médias.',
    ],

    // ==========================================
    // 3. SOFT SKILLS & DÉVELOPPEMENT PERSONNEL (DPS) - 11 formations (1 Semaine / 1900€)
    // ==========================================
    [
        'code' => 'DPS-001',
        'title' => 'Accueil physique et téléphonique des usagers',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Optimiser la qualité de l\'accueil, valoriser l\'image de l\'institution et gérer efficacement les demandes des usagers.',
    ],
    [
        'code' => 'DPS-002',
        'title' => 'Gestion de conflits et des situations difficiles',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Désamorcer les tensions, pratiquer la communication non violente et transformer les oppositions en opportunités constructives.',
    ],
    [
        'code' => 'DPS-003',
        'title' => 'Gestion du temps et des priorités',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Savoir distinguer l\'urgent de l\'important, éliminer les chronophages et organiser son planning avec méthode.',
    ],
    [
        'code' => 'DPS-004',
        'title' => 'Communication interpersonnelle et affirmation de soi (assertivité)',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Développer son assertivité, s\'exprimer clairement sans agressivité et instaurer des relations de confiance durable.',
    ],
    [
        'code' => 'DPS-005',
        'title' => 'Prise de parole en public et techniques de présentation',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Captiver son auditoire, maîtriser son langage corporel et structurer un pitch percutant et mémorable.',
    ],
    [
        'code' => 'DPS-006',
        'title' => 'Gestion du stress et prévention du burnout',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Comprendre les mécanismes du stress professionnel, adopter des techniques de récupération et préserver son équilibre de vie.',
    ],
    [
        'code' => 'DPS-007',
        'title' => 'Intelligence émotionnelle au travail',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Identifier ses émotions et celles des autres pour améliorer la prise de décision, l\'empathie et la collaboration.',
    ],
    [
        'code' => 'DPS-008',
        'title' => 'Travail en équipe et dynamique de groupe',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Renforcer la cohésion d\'équipe, instaurer une synergie positive et dépasser les individualismes.',
    ],
    [
        'code' => 'DPS-009',
        'title' => 'Leadership et développement du potentiel managérial',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Inspirer ses collaborateurs, déléguer avec discernement et développer une vision stratégique mobilisatrice.',
    ],
    [
        'code' => 'DPS-010',
        'title' => 'Négociation et résolution constructive des différends',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Préparer ses arguments, adopter une posture gagnant-gagnant et clore des accords pérennes et équilibrés.',
    ],
    [
        'code' => 'DPS-011',
        'title' => 'Posture professionnelle, déontologie et éthique de service',
        'type' => 'certifiante',
        'domain' => 'Soft Skills & Développement Personnel',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Incarner les valeurs de rigueur, de probité et d\'exemplarité au sein de son environnement de travail quotidien.',
    ],

    // ==========================================
    // 4. E-COMMERCE & FINTECH (EF) - 14 formations (1 Semaine / 1900€)
    // ==========================================
    [
        'code' => 'EF-001',
        'title' => 'Fondamentaux du commerce électronique et business models digitaux',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Comprendre les modèles économiques du commerce digital, les chaînes de valeur en ligne et les opportunités de monétisation.',
    ],
    [
        'code' => 'EF-002',
        'title' => 'Conception et gestion d\'une boutique en ligne',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Déployer, administrer et animer une plateforme e-commerce optimisée pour l\'expérience utilisateur et la conversion.',
    ],
    [
        'code' => 'EF-003',
        'title' => 'Marketing digital et stratégies d\'acquisition client pour l\'e-commerce',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Maîtriser les canaux d\'acquisition digitaux (SEO, SEA, réseaux sociaux, retargeting) pour générer des ventes rentables.',
    ],
    [
        'code' => 'EF-004',
        'title' => 'Paiement électronique, sécurité des transactions et conformité',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Intégrer les passerelles de paiement sécurisées, prévenir les fraudes en ligne et respecter les normes de conformité (PCI-DSS).',
    ],
    [
        'code' => 'EF-005',
        'title' => 'Logistique, chaîne d\'approvisionnement et livraison pour l\'e-commerce',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Organiser le stockage, la préparation de commande et la livraison du dernier kilomètre pour maximiser la satisfaction client.',
    ],
    [
        'code' => 'EF-006',
        'title' => 'Introduction aux technologies financières (Fintech)',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Panorama complet de l\'écosystème Fintech, des néobanques aux solutions d\'assurance connectée (Insurtech).',
    ],
    [
        'code' => 'EF-007',
        'title' => 'Réglementation et conformité dans le secteur des Fintechs',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Maîtriser les obligations légales de lutte contre le blanchiment (LCB-FT), la conformité réglementaire et les sandboxes prudentielles.',
    ],
    [
        'code' => 'EF-008',
        'title' => 'Cryptomonnaies, blockchain et applications financières décentralisées',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Comprendre le protocole blockchain, les smart contracts et les usages concrets de la finance décentralisée (DeFi).',
    ],
    [
        'code' => 'EF-009',
        'title' => 'Les Fintechs contre le changement climatique',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Découvrir le rôle de la Green Fintech et de la finance durable pour financer la transition énergétique et l\'action climatique.',
    ],
    [
        'code' => 'EF-010',
        'title' => 'Inclusion financière et solutions Fintech dans les pays émergents',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Accélérer l\'inclusion financière grâce au Mobile Money, aux micro-crédits digitaux et aux solutions adaptées aux populations non bancarisées.',
    ],
    [
        'code' => 'EF-011',
        'title' => 'Cybersécurité et gestion des risques dans les services financiers digitaux',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Protéger les actifs financiers numériques contre le piratage, l\'usurpation d\'identité et les vulnérabilités applicatives.',
    ],
    [
        'code' => 'EF-012',
        'title' => 'Open banking, API financières et partenariats stratégiques',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Exploiter les API bancaires ouvertes pour concevoir des services financiers à forte valeur ajoutée et nouer des partenariats innovants.',
    ],
    [
        'code' => 'EF-013',
        'title' => 'Crowdfunding, peer-to-peer lending et nouveaux modes de financement',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Mobiliser l\'épargne collective par le financement participatif, le prêt participatif et les plateformes de crowd-investing.',
    ],
    [
        'code' => 'EF-014',
        'title' => 'L\'Intelligence Artificielle (IA) appliquée aux entreprises',
        'type' => 'certifiante',
        'domain' => 'E-Commerce, Fintech & Développement Durable',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Découvrir comment exploiter les outils d\'IA générative, le machine learning et l\'analyse de données pour automatiser les processus d\'affaires.',
    ],

    // ==========================================
    // 5. INFORMATIQUE ET NOUVELLES TECHNOLOGIES (INT) - 13 formations (1 Semaine / 1900€)
    // ==========================================
    [
        'code' => 'INT-001',
        'title' => 'Audit de sécurité des réseaux et des systèmes d\'information',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Conduire des audits techniques, détecter les failles d\'infrastructure et sécuriser le périmètre réseau de l\'entreprise.',
    ],
    [
        'code' => 'INT-002',
        'title' => 'Audit de la sécurité des applications Web',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Identifier les vulnérabilités applicatives (top 10 OWASP), mener des tests d\'intrusion (pentesting) et sécuriser le code applicatif.',
    ],
    [
        'code' => 'INT-003',
        'title' => 'Investigation numérique & Computer Forensics',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Acquérir les techniques de collecte, préservation et analyse des preuves numériques lors de cyberattaques ou fraudes informatiques.',
    ],
    [
        'code' => 'INT-004',
        'title' => 'Administration et sécurisation des serveurs Linux',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Maîtriser les commandes avancées, durcir la configuration système, gérer les droits d\'accès et automatiser les sauvegardes sous Linux.',
    ],
    [
        'code' => 'INT-005',
        'title' => 'Administration et sécurisation des réseaux d\'entreprise',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Configurer les routeurs, switchs, pare-feux et VPN pour garantir une connectivité performante et hautement protégée.',
    ],
    [
        'code' => 'INT-006',
        'title' => 'Cloud Computing et virtualisation d\'infrastructures',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Migrer et gérer des charges de travail sur les principaux clouds publics (AWS, Azure) et maîtriser les hyperviseurs de virtualisation.',
    ],
    [
        'code' => 'INT-007',
        'title' => 'Gestion des incidents de sécurité et réponse à incident',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Mettre en place une cellule CSIRT/SOC, contenir les menaces actives et rétablir les services dans les meilleurs délais.',
    ],
    [
        'code' => 'INT-008',
        'title' => 'Gouvernance et management des systèmes d\'information (COBIT / ITIL)',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Aligner le SI sur les objectifs stratégiques, optimiser la gestion des services informatiques et appliquer les meilleures pratiques ITIL.',
    ],
    [
        'code' => 'INT-009',
        'title' => 'Analyse de données et Business Intelligence avec Power BI',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Collecter, modéliser et visualiser les données de gestion pour concevoir des tableaux de bord décisionnels interactifs.',
    ],
    [
        'code' => 'INT-010',
        'title' => 'Développement d\'applications web modernes et API REST',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Concevoir des architectures applicatives robustes, sécurisées et évolutives basées sur des frameworks modernes et des API RESTful.',
    ],
    [
        'code' => 'INT-011',
        'title' => 'DevOps, intégration et déploiement continus (CI/CD)',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Automatiser les cycles de tests et de déploiements d\'applications avec Docker, Kubernetes et les pipelines d\'intégration continue.',
    ],
    [
        'code' => 'INT-012',
        'title' => 'Sécurité des bases de données et protection des données sensibles',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Chiffrer les données au repos et en transit, gérer les privilèges d\'accès et prévenir les injections SQL et exfiltrations de données.',
    ],
    [
        'code' => 'INT-013',
        'title' => 'Introduction à l\'Internet des Objets (IoT) et sécurité des objets connectés',
        'type' => 'certifiante',
        'domain' => 'Informatique & NTIC',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Comprendre les architectures IoT, les protocoles de communication machine-to-machine et la sécurisation des périphériques connectés.',
    ],

    // ==========================================
    // 6. AUDIT, COMPTABILITÉ & FINANCE (ACF) - 28 formations (2 Semaines / 3300€)
    // ==========================================
    [
        'code' => 'ACF-001',
        'title' => 'Principes de la comptabilité publique',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Comprenez les règles et mécanismes clés de la comptabilité publique pour assurer une gestion efficace et transparente des finances publiques.',
    ],
    [
        'code' => 'ACF-002',
        'title' => 'Comptabilité analytique selon la méthode ABC',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtrisez la méthode ABC pour analyser les coûts par activité et améliorer la rentabilité et la performance de votre organisation.',
    ],
    [
        'code' => 'ACF-003',
        'title' => 'La comptabilité analytique: un outil d\'aide à la décision',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtrisez les méthodes d\'analyse des coûts pour optimiser les performances et guider les choix stratégiques de votre organisation.',
    ],
    [
        'code' => 'ACF-004',
        'title' => 'Comptabilité matière et gestion prévisionnelle des stocks',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtrisez les outils de gestion des stocks pour anticiper les besoins, réduire les coûts et améliorer la performance de votre organisation.',
    ],
    [
        'code' => 'ACF-005',
        'title' => 'Etre chef comptable: maitriser les aspects fondamentaux',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtrisez les missions clés du chef comptable pour piloter efficacement la comptabilité et assurer la conformité des opérations financières.',
    ],
    [
        'code' => 'ACF-006',
        'title' => 'Comptabilité & Fiscalité des immobilisations',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtrisez le traitement comptable et fiscal des immobilisations pour garantir la conformité et optimiser la gestion du patrimoine de l\'entreprise.',
    ],
    [
        'code' => 'ACF-007',
        'title' => 'Comprendre les normes comptables internationales & réussir le reporting',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Apprenez à appliquer les normes IFRS pour un reporting financier clair, fiable et conforme aux exigences.',
    ],
    [
        'code' => 'ACF-008',
        'title' => 'Financement de projets : Évaluer les risques et établir un plan de financement',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtrisez l\'évaluation des risques et la planification financière pour garantir le succès et la viabilité des projets.',
    ],
    [
        'code' => 'ACF-009',
        'title' => 'Comprendre les normes comptables IAS/IFRS',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtrisez les normes IAS/IFRS pour garantir un reporting financier conforme et transparent.',
    ],
    [
        'code' => 'ACF-010',
        'title' => 'Finance pour non-financiers : comprendre et interpréter les états financiers',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Déchiffrer le bilan, le compte de résultat et le tableau de flux pour dialoguer efficacement avec les financiers.',
    ],
    [
        'code' => 'ACF-011',
        'title' => 'Diagnostic financier de l\'entreprise',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Analyser la solvabilité, la liquidité et la rentabilité d\'une entreprise à travers ses ratios financiers fondamentaux.',
    ],
    [
        'code' => 'ACF-012',
        'title' => 'Gestion de la trésorerie et relation avec les banques',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Optimiser les prévisions de flux de trésorerie, négocier les conditions bancaires et sécuriser les liquidités de l\'entreprise.',
    ],
    [
        'code' => 'ACF-013',
        'title' => 'Élaboration et suivi du plan de financement à moyen et long terme',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Construire des plans de financement prévisionnels cohérents et équilibrer les ressources stables face aux investissements.',
    ],
    [
        'code' => 'ACF-014',
        'title' => 'Évaluation des investissements et choix de financement',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Arbitrer entre autofinancement, dette et levée de fonds en utilisant les critères de rentabilité financière.',
    ],
    [
        'code' => 'ACF-015',
        'title' => 'Audit financier et comptable : démarche, méthodes et outils',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtriser la méthodologie d\'audit légal et contractuel, la collecte des preuves et la rédaction des rapports d\'audit.',
    ],
    [
        'code' => 'ACF-016',
        'title' => 'Audit interne : organisation, méthodologie et normes internationales',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Mettre en place une charte d\'audit interne selon les normes de l\'IIA, élaborer les plans d\'audit et suivre les recommandations.',
    ],
    [
        'code' => 'ACF-017',
        'title' => 'Cartographie des risques financiers et contrôle interne',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Identifier les zones de vulnérabilité financière, concevoir la matrice des risques et renforcer les procédures de contrôle interne (COSO).',
    ],
    [
        'code' => 'ACF-018',
        'title' => 'Audit fiscal de l\'entreprise et gestion du risque fiscal',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Détecter les anomalies et risques fiscaux avant un contrôle de l\'administration et sécuriser les positions prises.',
    ],
    [
        'code' => 'ACF-019',
        'title' => 'Détection et prévention des fraudes financières et comptables',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Connaître les schémas classiques de fraude interne et externe, mettre en place des alertes et conduire des investigations.',
    ],
    [
        'code' => 'ACF-020',
        'title' => 'Fiscalité des entreprises : règles d\'assiette, déclaration et optimisation légale',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtriser le calcul de l\'impôt sur les sociétés (IS), les déductions autorisées et les déclarations fiscales annuelles.',
    ],
    [
        'code' => 'ACF-021',
        'title' => 'Fiscalité internationale et gestion des prix de transfert',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Comprendre les conventions fiscales internationales, la documentation des prix de transfert et les règles anti-évasion.',
    ],
    [
        'code' => 'ACF-022',
        'title' => 'TVA et taxes indirectes : règles de liquidation et de récupération',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Sécuriser le traitement de la TVA collectée et déductible, les règles de territorialité et les remboursements de crédit de TVA.',
    ],
    [
        'code' => 'ACF-023',
        'title' => 'Contrôle fiscal : droits, obligations et gestion du contentieux',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Préparer l\'entreprise à la vérification de comptabilité, formuler des réponses motivées aux redressements et gérer les recours.',
    ],
    [
        'code' => 'ACF-024',
        'title' => 'Consolidation des comptes selon les normes locales et internationales',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtriser les opérations d\'élimination réciproque, le périmètre de consolidation et l\'intégration globale et proportionnelle.',
    ],
    [
        'code' => 'ACF-025',
        'title' => 'Analyse de la rentabilité et tableaux de bord financiers',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Concevoir des indicateurs clés de rentabilité économique et financière (ROA, ROE) pour éclairer la direction générale.',
    ],
    [
        'code' => 'ACF-026',
        'title' => 'Gestion financière des collectivités territoriales',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Spécificités budgétaires des communes et régions, équilibre financier local et autofinancement des équipements collectifs.',
    ],
    [
        'code' => 'ACF-027',
        'title' => 'Comptabilité des sociétés et opérations sur capital',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Comptabiliser les augmentations et réductions de capital, l\'affectation des résultats et les opérations de fusion-acquisition.',
    ],
    [
        'code' => 'ACF-028',
        'title' => 'Gestion des risques de change et de taux d\'intérêt',
        'type' => 'certifiante',
        'domain' => 'Audit, Comptabilité & Finance',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Utiliser les instruments de couverture (terme, options, swaps) pour neutraliser les fluctuations monétaires sur les flux d\'import/export.',
    ],

    // ==========================================
    // 7. CONTRÔLE DE GESTION (GC) - 14 formations
    // ==========================================
    [
        'code' => 'GC-001',
        'title' => 'Fondamentaux du contrôle de gestion : principes, rôles et outils',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Acquérir la vision d\'ensemble du contrôle de gestion, ses méthodes d\'analyse et son positionnement d\'aide au pilotage.',
    ],
    [
        'code' => 'GC-002',
        'title' => 'Construction et pilotage budgétaire : prévision, suivi et arbitrage',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Maîtriser le cycle budgétaire annuel, de la lettre de cadrage aux révisions périodiques et arbitrages stratégiques.',
    ],
    [
        'code' => 'GC-003',
        'title' => 'Tableaux de bord de gestion et Balanced Scorecard',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Concevoir un tableau de bord équilibré intégrant les perspectives financière, client, processus et apprentissage.',
    ],
    [
        'code' => 'GC-004',
        'title' => 'Conception et suivi des indicateurs clés de performance (KPI)',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Sélectionner des KPI pertinents, automatiser leur calcul et mettre en place des alertes pour décider rapidement.',
    ],
    [
        'code' => 'GC-005',
        'title' => 'Contrôle de gestion commercial et analyse de la rentabilité client',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Analyser les marges par segment de clientèle, par canal de distribution et optimiser la politique tarifaire.',
    ],
    [
        'code' => 'GC-006',
        'title' => 'Contrôle de gestion industriel : calcul des coûts de revient et suivi des rendements',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Calculer les coûts standards de production, analyser les écarts sur matières et main-d\'œuvre et optimiser l\'utilisation des machines.',
    ],
    [
        'code' => 'GC-007',
        'title' => 'Contrôle de gestion des ressources humaines et pilotage de la masse salariale',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Mesurer l\'effet de noria, les glissements et promotions, et bâtir des prévisions rigoureuses d\'évolution de la masse salariale.',
    ],
    [
        'code' => 'GC-008',
        'title' => 'Contrôle de gestion dans le secteur des services et organisations publiques',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Adapter les outils de gestion aux activités immatérielles, mesurer les coûts des prestations et la qualité de service.',
    ],
    [
        'code' => 'GC-009',
        'title' => 'Analyse des écarts budgétaires et plans d\'actions correctives',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Décomposer les écarts sur chiffre d\'affaires et sur coûts, en identifier les causes réelles et structurer les plans d\'action.',
    ],
    [
        'code' => 'GC-010',
        'title' => 'Maîtrise des coûts cachés et management de la valeur',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Identifier les coûts de non-qualité, d\'absentéisme et de dysfonctionnement pour libérer des marges de productivité.',
    ],
    [
        'code' => 'GC-011',
        'title' => 'Business Plan et modélisation financière sous Excel',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Bâtir un modèle financier dynamique sous tableur pour tester la viabilité de nouveaux projets et investissements.',
    ],
    [
        'code' => 'GC-012',
        'title' => 'Contrôle de gestion de projet : planification et suivi des coûts',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Maîtriser la méthode de la valeur acquise (EVM), suivre les budgets engagés et anticiper les dérives de coût.',
    ],
    [
        'code' => 'GC-013',
        'title' => 'Animation du dialogue de gestion avec les opérationnels',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Développer une posture de business partner, responsabiliser les managers de terrain et donner du sens aux chiffres.',
    ],
    [
        'code' => 'GC-014',
        'title' => 'Diagnostic de performance globale et transformation du contrôle de gestion',
        'type' => 'certifiante',
        'domain' => 'Contrôle de Gestion',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Conduire un audit complet de la fonction contrôle de gestion, digitaliser les processus de reporting et aligner la performance sur la stratégie.',
    ],

    // ==========================================
    // 8. MARCHÉS PUBLICS (MP) - 14 formations (2 Semaines / 3300€)
    // ==========================================
    [
        'code' => 'MP-001',
        'title' => 'Exécution des marchés publics : suivi des contrats',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Sécuriser la passation et la gestion administrative, financière et juridique des marchés publics.',
    ],
    [
        'code' => 'MP-002',
        'title' => 'Cadre juridique et réglementaire de la commande publique',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtriser les principes fondamentaux de liberté d\'accès, d\'égalité de traitement et de transparence des procédures d\'achat public.',
    ],
    [
        'code' => 'MP-003',
        'title' => 'Préparation et rédaction des dossiers d\'appel d\'offres (DAO / RPAO)',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Rédiger des cahiers des charges précis (CCTP, CCAP), définir les critères de notation et éviter les clauses restrictives.',
    ],
    [
        'code' => 'MP-004',
        'title' => 'Procédures de passation des marchés de travaux, fournitures et services',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Choisir la procédure adéquate (appel d\'offres ouvert, restreint, entente directe) selon les seuils réglementaires et les délais.',
    ],
    [
        'code' => 'MP-005',
        'title' => 'Dépouillement, analyse et évaluation des offres',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Animer la commission d\'ouverture des plis, vérifier la conformité administrative, évaluer les offres techniques et financières.',
    ],
    [
        'code' => 'MP-006',
        'title' => 'Gestion contractuelle, avenants et révisions de prix des marchés',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Encadrer juridiquement les modifications en cours d\'exécution, rédiger les avenants réguliers et appliquer les formules de révision.',
    ],
    [
        'code' => 'MP-007',
        'title' => 'Réception des prestations, garanties et règlement financier des marchés',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Organiser les réceptions provisoires et définitives, libérer les cautions de retenue de garantie et traiter le décompte général définitif (DGD).',
    ],
    [
        'code' => 'MP-008',
        'title' => 'Gestion des litiges, réclamations et contentieux des marchés publics',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Gérer les mémoires de réclamation des entreprises, privilégier le règlement amiable et défendre les intérêts de l\'acheteur public.',
    ],
    [
        'code' => 'MP-009',
        'title' => 'Audit et contrôle de la passation et de l\'exécution des marchés',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Contrôler la régularité des actes de passation, vérifier l\'effectivité des livraisons et prévenir les sanctions des organes de contrôle.',
    ],
    [
        'code' => 'MP-010',
        'title' => 'Passation des marchés selon les directives des bailleurs internationaux (Banque Mondiale, BAD, UE)',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Maîtriser les règlements de passation des marchés des partenaires techniques et financiers pour éviter les avis de non-objection défavorables.',
    ],
    [
        'code' => 'MP-011',
        'title' => 'Dématérialisation et e-procurement dans la commande publique',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Déployer les plateformes électroniques de soumission, gérer les signatures électroniques et sécuriser les échanges numériques.',
    ],
    [
        'code' => 'MP-012',
        'title' => 'Partenariats Public-Privé (PPP) : montage et suivi des contrats',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Comprendre les spécificités des contrats de délégation de service public et concessions, et piloter les engagements à long terme.',
    ],
    [
        'code' => 'MP-013',
        'title' => 'Prévention de la corruption et déontologie dans les marchés publics',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Mettre en œuvre les codes de conduite éthique, déclarer les conflits d\'intérêts et renforcer l\'intégrité des acheteurs publics.',
    ],
    [
        'code' => 'MP-014',
        'title' => 'Achat public durable et responsabilité sociétale dans les marchés',
        'type' => 'certifiante',
        'domain' => 'Marchés Publics',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Intégrer les critères environnementaux et les clauses sociales d\'insertion dans les consultations pour un achat responsable.',
    ],

    // ==========================================
    // 9. SECRÉTARIAT & ARCHIVE BUREAU D'ORDRE (SAB) - 14 formations (1 Semaine / 1900€)
    // ==========================================
    [
        'code' => 'SAB-001',
        'title' => 'Organisation et fonctionnement moderne du bureau d\'ordre',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Structurer les flux d\'information entrants et sortants, mettre en place les registres et optimiser les circuits de validation.',
    ],
    [
        'code' => 'SAB-002',
        'title' => 'Gestion du courrier physique et électronique (enregistrement, imputation, traçabilité)',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Assurer la réception, l\'enregistrement chronologique, l\'imputation aux services compétents et le suivi rigoureux des délais de réponse.',
    ],
    [
        'code' => 'SAB-003',
        'title' => 'Techniques modernes d\'archivage physique et de gestion des dossiers',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Classer avec rigueur, concevoir un plan de classement efficace et sécuriser la conservation des archives courantes et intermédiaires.',
    ],
    [
        'code' => 'SAB-004',
        'title' => 'Gestion Électronique de Documents (GED) et dématérialisation',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Numériser les fonds documentaires, indexer les métadonnées et administrer une plateforme de GED collaborative.',
    ],
    [
        'code' => 'SAB-005',
        'title' => 'Rédaction administrative : notes, procès-verbaux, rapports et correspondances officielles',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Maîtriser les formules administratives d\'usage, la clarté rédactionnelle et la mise en forme irréprochable des documents officiels.',
    ],
    [
        'code' => 'SAB-006',
        'title' => 'Rôle et compétences de l\'assistante de direction d\'excellence',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Développer une collaboration proactive avec son responsable, anticiper les besoins et faire preuve de discrétion absolue.',
    ],
    [
        'code' => 'SAB-007',
        'title' => 'Gestion du temps, de l\'agenda et des priorités du manager',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Optimiser l\'emploi du temps de la direction, filtrer les sollicitations et gérer les imprévus avec sang-froid.',
    ],
    [
        'code' => 'SAB-008',
        'title' => 'Accueil physique et téléphonique des usagers et partenaires',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Offrir un accueil professionnel et courtois, orienter efficacement les visiteurs et valoriser l\'image de marque de l\'organisation.',
    ],
    [
        'code' => 'SAB-009',
        'title' => 'Organisation d\'événements, réunions et missions professionnelles',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Planifier la logistique des conseils et séminaires, coordonner les déplacements et veiller au respect des budgets alloués.',
    ],
    [
        'code' => 'SAB-010',
        'title' => 'Classement, conservation légale et archivage patrimonial des documents',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Respecter la durée d\'utilité administrative (DUA), organiser les éliminations légales et verser les archives historiques.',
    ],
    [
        'code' => 'SAB-011',
        'title' => 'Sécurité, confidentialité et protection des données administratives',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Prévenir les fuites d\'informations confidentielles, appliquer le secret professionnel et sécuriser l\'accès aux locaux d\'archives.',
    ],
    [
        'code' => 'SAB-012',
        'title' => 'Outils bureautiques avancés (Word, Excel, PowerPoint) pour le secrétariat',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Automatiser le publipostage, créer des tableaux de bord de suivi et concevoir des présentations visuelles de haut niveau.',
    ],
    [
        'code' => 'SAB-013',
        'title' => 'Communication interne et relation avec les directions opérationnelles',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Faciliter la circulation transversale de l\'information, relancer les services avec diplomatie et maintenir un climat coopératif.',
    ],
    [
        'code' => 'SAB-014',
        'title' => 'Déontologie, éthique professionnelle et image de marque de l\'institution',
        'type' => 'certifiante',
        'domain' => 'Secrétariat & Archive Bureau d\'Ordre',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Cultiver les valeurs de neutralité, de loyauté et de sens du service public dans toutes les missions administratives.',
    ],

    // ==========================================
    // 10. GRH, & MANAGEMENT DES ORGANISATIONS (GMO) - 23 formations (2 Semaines / 3300€)
    // ==========================================
    [
        'code' => 'GMO-001',
        'title' => 'Fondements et évolution de la gestion des ressources humaines',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Comprendre les mutations de la fonction RH, de l\'administration du personnel au rôle de partenaire stratégique de la direction.',
    ],
    [
        'code' => 'GMO-002',
        'title' => 'Gestion Prévisionnelle des Emplois et des Compétences (GPEC)',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Anticiper les besoins futurs en compétences, élaborer les référentiels métiers et bâtir les passerelles de mobilité professionnelle.',
    ],
    [
        'code' => 'GMO-003',
        'title' => 'Processus de recrutement, sélection et intégration des talents',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Conduire des entretiens d\'embauche structurés, évaluer les soft skills et réussir l\'onboarding des nouveaux collaborateurs.',
    ],
    [
        'code' => 'GMO-004',
        'title' => 'Élaboration, pilotage et évaluation du plan de formation',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Recueillir les besoins de compétences, construire un plan de formation aligné sur la stratégie et mesurer le retour sur investissement (ROI).',
    ],
    [
        'code' => 'GMO-005',
        'title' => 'Évaluation des performances et conduite des entretiens annuels',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Fixer des objectifs mesurables, mener l\'entretien d\'évaluation avec bienveillance et objectivité, et définir les plans de développement.',
    ],
    [
        'code' => 'GMO-006',
        'title' => 'Politique de rémunération, avantages sociaux et masse salariale',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Bâtir une grille salariale équitable et compétitive, concevoir des systèmes de primes motivants et maîtriser la masse salariale.',
    ],
    [
        'code' => 'GMO-007',
        'title' => 'Droit du travail, gestion des contrats et relations individuelles',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Sécuriser la rédaction des contrats de travail, gérer les modifications contractuelles et maîtriser les procédures disciplinaires et de rupture.',
    ],
    [
        'code' => 'GMO-008',
        'title' => 'Dialogue social, négociation collective et gestion des relations avec les représentants du personnel',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Instaurer un climat social serein, animer les instances représentatives et négocier des accords collectifs équilibrés.',
    ],
    [
        'code' => 'GMO-009',
        'title' => 'Hygiène, santé et sécurité au travail (obligations et politiques de prévention)',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Respecter le cadre réglementaire de sécurité au travail, identifier les risques professionnels et mettre en œuvre les mesures de prévention.',
    ],
    [
        'code' => 'GMO-010',
        'title' => 'Qualité de vie au travail (QVT), bien-être et prévention des risques psychosociaux (RPS)',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Promouvoir un environnement de travail épanouissant, dépister les signes de surmenage et prévenir les conflits destructeurs.',
    ],
    [
        'code' => 'GMO-011',
        'title' => 'Tableaux de bord RH, SIRH et indicateurs clés de la performance RH',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Concevoir des indicateurs clés (turnover, absentéisme, pyramide des âges) et exploiter les données pour guider les décisions RH.',
    ],
    [
        'code' => 'GMO-012',
        'title' => 'Management de la diversité, équité et inclusion en entreprise',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Valoriser tous les profils, combattre les discriminations et transformer la mixité des équipes en levier de créativité.',
    ],
    [
        'code' => 'GMO-013',
        'title' => 'Conduite du changement et accompagnement des transformations organisationnelles',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Diagnostiquer les résistances au changement, communiquer de façon rassurante et mobiliser les équipes autour de nouveaux projets.',
    ],
    [
        'code' => 'GMO-014',
        'title' => 'Leadership managérial et posture du manager coach',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Développer l\'autonomie de ses collaborateurs, pratiquer l\'écoute active et accompagner la progression individuelle.',
    ],
    [
        'code' => 'GMO-015',
        'title' => 'Gestion des conflits, médiation et climat social',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Désamorcer les tensions relationnelles, intervenir en médiateur impartial et rétablir la coopération au sein des services.',
    ],
    [
        'code' => 'GMO-016',
        'title' => 'Organisation du travail, télétravail et modes de collaboration hybrides',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Encadrer le travail à distance, maintenir le lien d\'équipe et adapter les pratiques managériales aux modes hybrides.',
    ],
    [
        'code' => 'GMO-017',
        'title' => 'Responsabilité Sociétale des Entreprises (RSE) appliquée aux ressources humaines',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Intégrer les critères environnementaux, sociaux et de gouvernance (ESG) dans les politiques de gestion des talents.',
    ],
    [
        'code' => 'GMO-018',
        'title' => 'Audit social et conformité réglementaire des pratiques RH',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Évaluer la conformité des pratiques RH avec la législation, identifier les risques prud\'homaux et sécuriser les processus.',
    ],
    [
        'code' => 'GMO-019',
        'title' => 'Marque employeur et fidélisation des talents clés',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Valoriser l\'attractivité de l\'entreprise, soigner l\'expérience collaborateur et fidéliser les compétences stratégiques.',
    ],
    [
        'code' => 'GMO-020',
        'title' => 'Management stratégique des organisations et gouvernance d\'entreprise',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Comprendre les mécanismes de gouvernance, la répartition des pouvoirs et l\'alignement stratégique des structures.',
    ],
    [
        'code' => 'GMO-021',
        'title' => 'Optimisation des processus et diagnostic organisationnel',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Cartographier les processus métiers, éliminer les goulets d\'étranglement et fluidifier l\'organisation du travail.',
    ],
    [
        'code' => 'GMO-022',
        'title' => 'Culture d\'entreprise, valeurs partagées et engagement des collaborateurs',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Renforcer le sentiment d\'appartenance, transmettre la vision d\'entreprise et stimuler l\'engagement au travail.',
    ],
    [
        'code' => 'GMO-023',
        'title' => 'Management interculturel et pilotage des équipes multiculturelles',
        'type' => 'certifiante',
        'domain' => 'GRH, & Management des Organisations',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Décoder les différences culturelles, adapter son style de communication et tirer parti de la diversité culturelle.',
    ],

    // ==========================================
    // 11. QUALITE HYGIENE & SECURITE ENVIRONNEMENTALE (QHSE) - 14 formations (1 Semaine / 1900€)
    // ==========================================
    [
        'code' => 'QHSE-001',
        'title' => 'Fondamentaux du management de la Qualité, Hygiène, Sécurité et Environnement (QHSE)',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Appréhender les enjeux globaux du management intégré QHSE et les responsabilités juridiques des dirigeants et préventeurs.',
    ],
    [
        'code' => 'QHSE-002',
        'title' => 'Mise en place et audit d\'un Système de Management Intégré (SMI)',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Concevoir et déployer une démarche intégrée combinant qualité, santé-sécurité et environnement avec une documentation allégée.',
    ],
    [
        'code' => 'QHSE-003',
        'title' => 'Norme ISO 9001 : exigences et déploiement du management de la qualité',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Maîtriser les clauses de l\'ISO 9001 version 2015, l\'approche par les risques et le pilotage de l\'amélioration continue.',
    ],
    [
        'code' => 'QHSE-004',
        'title' => 'Norme ISO 14001 : management environnemental et développement durable',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Identifier les aspects environnementaux significatifs (AES), mesurer l\'empreinte écologique et respecter les normes environnementales.',
    ],
    [
        'code' => 'QHSE-005',
        'title' => 'Norme ISO 45001 : management de la santé et de la sécurité au travail',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Structurer une démarche rigoureuse de prévention des risques professionnels conforme aux standards internationaux ISO 45001.',
    ],
    [
        'code' => 'QHSE-006',
        'title' => 'Évaluation des risques professionnels et document unique (EvRP)',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Identifier les dangers par unité de travail, coter la gravité et la fréquence et rédiger le plan d\'action de prévention des risques.',
    ],
    [
        'code' => 'QHSE-007',
        'title' => 'Hygiène et sécurité sur les lieux de travail : réglementation et bonnes pratiques',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Appliquer les règles d\'aération, d\'éclairage, d\'équipements de protection individuelle (EPI) et de propreté des locaux de travail.',
    ],
    [
        'code' => 'QHSE-008',
        'title' => 'Gestion des déchets, rejets industriels et transition écologique',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Organiser le tri, le traitement et la valorisation des déchets industriels et réduire les émissions polluantes de l\'entreprise.',
    ],
    [
        'code' => 'QHSE-009',
        'title' => 'Enquête, analyse des accidents du travail et méthode de l\'arbre des causes',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Mener une enquête après sinistre, remonter à la source des défaillances avec l\'arbre des causes et éviter toute récidive.',
    ],
    [
        'code' => 'QHSE-010',
        'title' => 'Plan d\'urgence, gestion de crise et sécurité incendie en entreprise',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Élaborer les plans d\'évacuation, organiser les exercices incendie et coordonner les secours en situation de crise grave.',
    ],
    [
        'code' => 'QHSE-011',
        'title' => 'Audit interne QHSE : préparation, réalisation et suivi des actions correctives',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Conduire des audits méthodiques selon l\'ISO 19011, notifier les constats et s\'assurer de l\'efficacité des actions correctives.',
    ],
    [
        'code' => 'QHSE-012',
        'title' => 'Culture de sécurité et sensibilisation des équipes aux comportements sûrs',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Développer les causeries sécurité, susciter l\'adhésion des opérateurs et transformer la sécurité en réflexe collectif partagé.',
    ],
    [
        'code' => 'QHSE-013',
        'title' => 'Ergonomie des postes de travail et prévention des troubles musculosquelettiques (TMS)',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Analyser les postures, aménager les postes physiques et informatiques et réduire significativement les TMS en entreprise.',
    ],
    [
        'code' => 'QHSE-014',
        'title' => 'Indicateurs de performance QHSE, tableaux de bord et reporting réglementaire',
        'type' => 'certifiante',
        'domain' => 'Qualité Hygiène & Sécurité Environnementale',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Suivre les taux de fréquence et de gravité, alimenter les bilans annuels et présenter des tableaux de bord clairs à la direction.',
    ],

    // ==========================================
    // 12. DROIT (OHADA) (DO) - 10 formations
    // ==========================================
    [
        'code' => 'DO-001',
        'title' => 'Droit général des affaires dans l\'espace OHADA',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '2 Semaines',
        'price' => 2900.00,
        'description' => 'Maîtriser les principes du statut du commerçant, du bail commercial, du fonds de commerce et des intermédiaires en droit OHADA.',
    ],
    [
        'code' => 'DO-002',
        'title' => 'Droit des sociétés commerciales et du GIE selon l\'Acte uniforme OHADA',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Choisir la forme sociale adaptée (SARL, SAS, SA), organiser la gouvernance et sécuriser les pactes d\'actionnaires.',
    ],
    [
        'code' => 'DO-003',
        'title' => 'Droit des sûretés et garanties de crédit en droit OHADA',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Sécuriser les financements par les sûretés personnelles (cautionnement, garantie autonome) et réelles (hypothèques, nantissements).',
    ],
    [
        'code' => 'DO-004',
        'title' => 'Procédures simplifiées de recouvrement et voies d\'exécution OHADA',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Mettre en œuvre l\'injonction de payer et de délivrer, pratiquer les saisies conservatoires et exécutoires avec efficacité.',
    ],
    [
        'code' => 'DO-005',
        'title' => 'Droit des contrats commerciaux internationaux et clauses sensibles',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Rédiger et négocier les clauses d\'imprévision, de force majeure, de limitation de responsabilité et de compétence juridictionnelle.',
    ],
    [
        'code' => 'DO-006',
        'title' => 'Droit de l\'arbitrage et médiation commerciale dans l\'espace OHADA',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Résoudre rapidement les litiges commerciaux par la sentence arbitrale ou l\'accord de médiation exécutoire.',
    ],
    [
        'code' => 'DO-007',
        'title' => 'Droit des entreprises en difficulté et procédures collectives d\'apurement du passif',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Mettre en œuvre les procédures préventives (conciliation, règlement préventif) et gérer les redressements et liquidations judiciaires.',
    ],
    [
        'code' => 'DO-009',
        'title' => 'Droit du travail et contentieux social comparé dans les pays africains',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Sécuriser la gestion des relations de travail, anticiper les risques de contentieux et maîtriser les règles de rupture du contrat.',
    ],
    [
        'code' => 'DO-010',
        'title' => 'Droit fiscal des affaires et conventions fiscales de non-double imposition',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Comprendre l\'articulation fiscale régionale et internationale pour optimiser légalement l\'imposition des flux transfrontaliers.',
    ],
    [
        'code' => 'DO-011',
        'title' => 'Pratique du contentieux commercial et stratégie judiciaire devant la CCJA',
        'type' => 'certifiante',
        'domain' => 'Droit des Affaires & Droit OHADA',
        'duration' => '2 Semaines',
        'price' => 2900.00,
        'description' => 'Maîtriser les voies de recours en cassation devant la Cour Commune de Justice et d\'Arbitrage (CCJA) d\'Abidjan.',
    ],

    // ==========================================
    // 13. DIGITALISATION DE L'ADMINISTRATION PUBLIQUE (DAP) - 14 formations (2 Semaines / 3300€)
    // ==========================================
    [
        'code' => 'DAP-010',
        'title' => 'Stratégie nationale de transformation numérique de l\'administration publique',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Concevoir une feuille de route e-gouvernement, aligner les projets ministériels et coordonner la transformation digitale de l\'État.',
    ],
    [
        'code' => 'DAP-011',
        'title' => 'Dématérialisation des procédures et des services publics aux usagers (E-Gouvernement)',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Simplifier les démarches administratives, supprimer les formulaires papier et créer des parcours usagers 100% en ligne.',
    ],
    [
        'code' => 'DAP-012',
        'title' => 'Conception et déploiement de portails citoyens et guichets uniques numériques',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Créer des guichets uniques accessibles, ergonomiques et sécurisés pour centraliser l\'accès aux services publics.',
    ],
    [
        'code' => 'DAP-013',
        'title' => 'Identité numérique, signature électronique et confiance numérique dans le secteur public',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Déployer les dispositifs d\'e-ID nationale, les certificats électroniques et garantir la valeur probante des actes numériques publics.',
    ],
    [
        'code' => 'DAP-014',
        'title' => 'Interopérabilité des systèmes d\'information publics et urbanisation des SI',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Bâtir des cadres d\'interopérabilité (API publiques, bus de données) pour faire communiquer les ministères et agences étatiques.',
    ],
    [
        'code' => 'DAP-015',
        'title' => 'Gestion du changement et accompagnement des agents publics vers la culture numérique',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Accompagner la montée en compétences des fonctionnaires, lever les freins culturels et instaurer des réflexes digitaux partagés.',
    ],
    [
        'code' => 'DAP-016',
        'title' => 'Sécurité des données publiques, RGPD et cadre légal de la protection des données personnelles',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Conformer les traitements de données publiques aux réglementations de protection de la vie privée et nommer un DPO public.',
    ],
    [
        'code' => 'DAP-017',
        'title' => 'Cybersécurité des infrastructures critiques et résilience des administrations publiques',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Protéger les registres nationaux et infrastructures vitales contre les cyberattaques, ransomwares et tentatives d\'espionnage.',
    ],
    [
        'code' => 'DAP-018',
        'title' => 'Données publiques ouvertes (Open Data), gouvernance de la donnée et transparence',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Ouvrir les données publiques, favoriser l\'innovation citoyenne et renforcer la transparence de l\'action gouvernementale.',
    ],
    [
        'code' => 'DAP-019',
        'title' => 'Intelligence Artificielle et automatisation des processus au service de l\'action publique',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Automatiser le traitement des dossiers administratifs par l\'IA, les chatbots citoyens et l\'analyse prédictive publique.',
    ],
    [
        'code' => 'DAP-020',
        'title' => 'Pilotage et management de projets numériques publics (méthodes agiles et traditionnelles)',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Piloter les grands projets informatiques de l\'État, respecter les délais et les budgets en combinant Scrum et méthodes classiques.',
    ],
    [
        'code' => 'DAP-021',
        'title' => 'E-Procurement et passation dématérialisée des marchés publics',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Gérer les portails de marchés publics électroniques, de la publication des avis à l\'attribution et signature électronique des contrats.',
    ],
    [
        'code' => 'DAP-022',
        'title' => 'Budget, financement et rentabilité des projets de transformation digitale publique',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Évaluer le coût total de possession (TCO) des solutions logicielles publiques et mesurer les gains d\'efficience générés.',
    ],
    [
        'code' => 'DAP-023',
        'title' => 'Évaluation de l\'impact, mesure de la satisfaction citoyenne et amélioration continue des e-services',
        'type' => 'certifiante',
        'domain' => 'Digitalisation de l\'Administration Publique',
        'duration' => '2 Semaines',
        'price' => 3300.00,
        'description' => 'Mettre en place des baromètres d\'usage, recueillir les retours des administrés et ajuster continuellement la qualité des téléprocédures.',
    ],

    // ==========================================
    // 14. MARKETING, COMMUNICATION & DISTRIBUTION (MCD) - 14 formations (1 Semaine / 1900€)
    // ==========================================
    [
        'code' => 'MCD-001',
        'title' => 'Fondements du marketing stratégique et opérationnel',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Définir la stratégie de ciblage, le positionnement de marque et décliner le mix marketing pour conquérir de nouveaux marchés.',
    ],
    [
        'code' => 'MCD-002',
        'title' => 'Marketing digital : SEO, SEA, content marketing et réseaux sociaux',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Bâtir une présence en ligne forte, optimiser son référencement naturel et payant et engager sa communauté sur les réseaux sociaux.',
    ],
    [
        'code' => 'MCD-003',
        'title' => 'Stratégie de marque (Branding), positionnement et identité visuelle',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Créer une marque mémorable, concevoir une charte graphique percutante et communiquer les valeurs fondamentales de l\'organisation.',
    ],
    [
        'code' => 'MCD-004',
        'title' => 'Communication institutionnelle et relations publiques',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Valoriser l\'image corporate auprès des médias, des institutions et du grand public, et gérer les dossiers de presse.',
    ],
    [
        'code' => 'MCD-005',
        'title' => 'Gestion de la communication de crise et e-réputation',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Anticiper les bad buzz, mettre en place une cellule de crise réactive et préserver la réputation de l\'entreprise face aux tempêtes médiatiques.',
    ],
    [
        'code' => 'MCD-006',
        'title' => 'Élaboration et pilotage d\'un plan de communication à 360 degrés',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Harmoniser les actions on-line et off-line, allouer les budgets médias et mesurer le retour sur investissement (ROAS).',
    ],
    [
        'code' => 'MCD-007',
        'title' => 'Stratégies de distribution, circuits de vente et gestion du réseau commercial',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Optimiser le maillage territorial, animer les revendeurs et concilier vente directe, grande distribution et commerce en ligne.',
    ],
    [
        'code' => 'MCD-008',
        'title' => 'Management de la force de vente, négociation et performance commerciale',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Fixer les quotas de vente, motiver les équipes commerciales et maîtriser les techniques de closing en B2B et B2C.',
    ],
    [
        'code' => 'MCD-009',
        'title' => 'Gestion de la relation client (CRM) et fidélisation',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Déployer des outils CRM performants, segmenter les bases de données clients et mettre en place des programmes de fidélisation rentables.',
    ],
    [
        'code' => 'MCD-010',
        'title' => 'Études de marché, analyse du comportement des consommateurs et veille concurrentielle',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Conduire des enquêtes quantitatives et qualitatives, analyser les tendances d\'achat et surveiller les initiatives concurrentes.',
    ],
    [
        'code' => 'MCD-011',
        'title' => 'Trade marketing, merchandising et promotion des ventes',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Optimiser la visibilité en point de vente (PLV, têtes de gondole) et concevoir des opérations promotionnelles percutantes.',
    ],
    [
        'code' => 'MCD-012',
        'title' => 'Événementiel professionnel et communication hors média',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Organiser des salons professionnels, des lancements de produits et des conférences pour marquer les esprits.',
    ],
    [
        'code' => 'MCD-013',
        'title' => 'Stratégie de fixation des prix (Pricing) et rentabilité commerciale',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Établir la bonne politique tarifaire selon la valeur perçue, la concurrence et les seuils de rentabilité économique.',
    ],
    [
        'code' => 'MCD-014',
        'title' => 'Storytelling, création de contenu impactant et marketing d\'influence',
        'type' => 'certifiante',
        'domain' => 'Marketing, Communication & Distribution',
        'duration' => '1 Semaine',
        'price' => 1900.00,
        'description' => 'Raconter une histoire émotionnelle forte, collaborer avec des créateurs de contenu influents et fidéliser son audience.',
    ],

            // ==========================================
            // 15. FORMATIONS DIPLOMANTES (MBA, DOCTORAT)
            // ==========================================
            [
                'code' => 'MBA-MINI',
                'title' => 'Mini MBA - Fondamentaux du Management Général',
                'type' => 'diplomante',
                'domain' => 'Management & Governance',
                'duration' => '6 mois',
                'price' => null, // Sur devis
                'description' => 'Programme condensé de haut niveau conçu pour les cadres à fort potentiel souhaitant consolider leurs compétences transversales en leadership, finance et stratégie.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'MBA-EXEC',
                'title' => 'Executive MBA (EMBA) - Leadership Stratégique',
                'type' => 'diplomante',
                'domain' => 'Management & Governance',
                'duration' => '12 mois',
                'price' => null, // Sur devis
                'description' => 'Un cursus international d excellence conciliable avec une carrière active, préparant aux postes de direction générale et internationale.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
            [
                'code' => 'DOC-EXEC',
                'title' => 'Doctorat Executive (DBA) - Recherche & Management Stratégique',
                'type' => 'diplomante',
                'domain' => 'Management & Governance',
                'duration' => '36 mois',
                'price' => null, // Sur devis
                'description' => 'Le plus haut niveau académique et professionnel pour concevoir des travaux de recherche appliquée aux problématiques réelles des organisations.',
                'status' => 'active',
                'created_by' => $adminId,
            ],
        ];

        foreach ($formations as $data) {
            if ($adminId && !isset($data['created_by'])) {
                $data['created_by'] = $adminId;
            }
            if (!isset($data['status'])) {
                $data['status'] = 'active';
            }
            Formation::updateOrCreate(
                ['code' => $data['code']],
                $data
            );
        }
    }
}